
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.ma||(f.ma=0);f.ma++;
(function(a){function b(n,v,t){var u=new XMLHttpRequest;u.open("GET",n,!0);u.responseType="arraybuffer";u.onprogress=function(w){var k=v;w.total&&(k=w.total);if(w.loaded){u.i?f.C[n].loaded=w.loaded:(u.i=!0,f.C||(f.C={}),f.C[n]={loaded:w.loaded,total:k});var x=k=w=0,y;for(y in f.C){var E=f.C[y];w+=E.total;k+=E.loaded;x++}w=Math.ceil(w*f.ma/x);f.setStatus&&f.setStatus("Downloading data... ("+k+"/"+w+")")}else!f.C&&f.setStatus&&f.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
n);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)t(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,k,x){this.start=w;this.ha=k;this.audio=x}function v(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.hb=w;w=a.files;for(var k=0;k<
w.length;++k)n.prototype.i[w[k].filename].onload();f.removeRunDependency("datafile_../Siv3DTest.data")}f.FS_createPath("/","resources",!0,!0);f.FS_createPath("/resources","engine",!0,!0);f.FS_createPath("/resources/engine","shader",!0,!0);f.FS_createPath("/resources/engine/shader","glsl",!0,!0);f.FS_createPath("/","test",!0,!0);f.FS_createPath("/test","binary",!0,!0);f.FS_createPath("/test","image",!0,!0);f.FS_createPath("/test/image","bmp",!0,!0);f.FS_createPath("/test/image","png",!0,!0);f.FS_createPath("/test",
"text",!0,!0);f.FS_createPath("/test/text","long",!0,!0);n.prototype={i:{},open:function(w,k){this.name=k;this.i[k]=this;f.addRunDependency("fp "+this.name)},onload:function(){this.gb(this.hb.subarray(this.start,this.ha))},gb:function(w){f.FS_createDataFile(this.name,null,w,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.i[this.name]=null}};for(var t=a.files,u=0;u<t.length;++u)(new n(t[u].start,t[u].end,t[u].audio)).open("GET",t[u].filename);f.addRunDependency("datafile_../Siv3DTest.data");
f.Na||(f.Na={});f.Na["../Siv3DTest.data"]={Mb:!1};m?(v(m),m=null):h=v}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof f.locateFilePackage||
f.locateFile||(f.locateFile=f.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=f.locateFile?f.locateFile("Siv3DTest.data",""):"Siv3DTest.data",g=a.remote_package_size,h=null,m=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;m||b(e,g,function(n){h?(h(n),h=null):m=n},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/resources/engine/shader/glsl/fullscreen_triangle.frag",
start:0,end:215,audio:0},{filename:"/resources/engine/shader/glsl/fullscreen_triangle.vert",start:215,end:471,audio:0},{filename:"/resources/engine/shader/glsl/shape.frag",start:471,end:756,audio:0},{filename:"/resources/engine/shader/glsl/sprite.vert",start:756,end:1368,audio:0},{filename:"/test/binary/empty.bin",start:1368,end:1368,audio:0},{filename:"/test/binary/large.bin",start:1368,end:131432,audio:0},{filename:"/test/binary/small.bin",start:131432,end:131687,audio:0},{filename:"/test/image/bmp/1x1_24.bmp",
start:131687,end:131745,audio:0},{filename:"/test/image/bmp/1x1_256.bmp",start:131745,end:132827,audio:0},{filename:"/test/image/bmp/3x3_24.bmp",start:132827,end:132917,audio:0},{filename:"/test/image/bmp/3x3_256.bmp",start:132917,end:134007,audio:0},{filename:"/test/image/png/1x1.png",start:134007,end:134127,audio:0},{filename:"/test/image/png/1x1_8.png",start:134127,end:134197,audio:0},{filename:"/test/image/png/3x3.png",start:134197,end:134330,audio:0},{filename:"/test/image/png/3x3_8.png",start:134330,
end:134452,audio:0},{filename:"/test/image/png/3x3_gray16.png",start:134452,end:135830,audio:0},{filename:"/test/text/empty.txt",start:135830,end:135830,audio:0},{filename:"/test/text/utf16_be.txt",start:135830,end:135842,audio:0},{filename:"/test/text/utf16_le.txt",start:135842,end:135854,audio:0},{filename:"/test/text/utf8_no_bom.txt",start:135854,end:135859,audio:0},{filename:"/test/text/utf8_with_bom.txt",start:135859,end:135867,audio:0},{filename:"/test/text/long/utf16_be.txt",start:135867,end:135939,
audio:0},{filename:"/test/text/long/utf16_le.txt",start:135939,end:136011,audio:0},{filename:"/test/text/long/utf8_no_bom.txt",start:136011,end:136058,audio:0},{filename:"/test/text/long/utf8_with_bom.txt",start:136058,end:136108,audio:0}],remote_package_size:136108,package_uuid:"d8d343e7-48c2-4d7e-a460-fba469f01b6e"});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ka=!1;fa="object"===typeof window;
ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ka=!fa&&!ia&&!ha;var p="",la,ma,na,oa,pa;
if(ia)p=ha?require("path").dirname(p)+"/":__dirname+"/",la=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);return oa.readFileSync(a,b?null:"utf8")},na=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;}),process.on("unhandledRejection",
q),ea=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ka)"undefined"!=typeof read&&(la=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?p=self.location.href:document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=function(a,
b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ra=f.print||console.log.bind(console),l=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);
function sa(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=Number(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function ta(a){ua||(ua={});ua[a]||(ua[a]=1,l(a))}var ua,va=0,wa;f.wasmBinary&&(wa=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);
"object"!==typeof WebAssembly&&q("no native wasm support detected");
function r(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":z[a>>0]=b;break;case "i8":z[a>>0]=b;break;case "i16":xa[a>>1]=b;break;case "i32":A[a>>2]=b;break;case "i64":B=[b>>>0,(C=b,1<=+ya(C)?0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[a>>2]=B[0];A[a+4>>2]=B[1];break;case "float":Ca[a>>2]=b;break;case "double":Da[a>>3]=b;break;default:q("invalid type for setValue: "+c)}}
var Ea,D=new WebAssembly.Table({initial:2E3,maximum:2E3,element:"anyfunc"}),Fa=!1;function assert(a,b){a||q("Assertion failed: "+b)}
function Ga(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var g=Ha(Math.max(d,e?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)A[a>>2]=0;for(b=g+d;a<b;)z[a++>>0]=0;return g}if("i8"===e)return a.subarray||a.slice?F.set(a,g):F.set(new Uint8Array(a),g),g;c=0;for(var h,m,n;c<d;){var v=a[c];h=e||b[c];0===h?c++:("i64"==h&&(h="i32"),r(g+c,v,h),n!==h&&(m=sa(h),n=h),c+=m)}return g}
var Ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ja(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?Ja(F,a,b):""}
function Ka(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Na(a){var b=Ma(a)+1,c=Ha(b);c&&Ka(a,z,c,b);return c}function Oa(a){var b=Ma(a)+1,c=Pa(b);Ka(a,z,c,b);return c}var Qa,z,F,xa,Ra,A,Sa,Ca,Da;
function Ta(a){Qa=a;f.HEAP8=z=new Int8Array(a);f.HEAP16=xa=new Int16Array(a);f.HEAP32=A=new Int32Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=Ra=new Uint16Array(a);f.HEAPU32=Sa=new Uint32Array(a);f.HEAPF32=Ca=new Float32Array(a);f.HEAPF64=Da=new Float64Array(a)}var Ua=f.INITIAL_MEMORY||16777216;f.wasmMemory?Ea=f.wasmMemory:Ea=new WebAssembly.Memory({initial:Ua/65536,maximum:32768});Ea&&(Qa=Ea.buffer);Ua=Qa.byteLength;Ta(Qa);var Va=[],Wa=[],Xa=[],Ya=[];
function Za(){var a=f.preRun.shift();Va.unshift(a)}var ya=Math.abs,Ba=Math.ceil,Aa=Math.floor,za=Math.min,$a=0,ab=null,bb=null;function cb(){$a++;f.monitorRunDependencies&&f.monitorRunDependencies($a)}function db(){$a--;f.monitorRunDependencies&&f.monitorRunDependencies($a);if(0==$a&&(null!==ab&&(clearInterval(ab),ab=null),bb)){var a=bb;bb=null;a()}}f.preloadedImages={};f.preloadedAudios={};
function q(a){if(f.onAbort)f.onAbort(a);l(a);Fa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function eb(a){var b=fb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function gb(){return eb("data:application/octet-stream;base64,")}var fb="Siv3DTest.wasm";if(!gb()){var hb=fb;fb=f.locateFile?f.locateFile(hb,p):p+hb}
function ib(){try{if(wa)return new Uint8Array(wa);if(na)return na(fb);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function jb(){return wa||!fa&&!ha||"function"!==typeof fetch||eb("file://")?Promise.resolve().then(ib):fetch(fb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+fb+"'";return a.arrayBuffer()}).catch(function(){return ib()})}var C,B;Wa.push({Ba:function(){kb()}});
function lb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Ba;"number"===typeof c?void 0===b.T?D.get(c)():D.get(c)(b.T):c(void 0===b.T?null:b.T)}}}function mb(a){this.s=a-16;this.wb=function(b){A[this.s+8>>2]=b};this.tb=function(b){A[this.s+0>>2]=b};this.ub=function(){A[this.s+4>>2]=0};this.sb=function(){z[this.s+12>>0]=0};this.vb=function(){z[this.s+13>>0]=0};this.jb=function(b,c){this.wb(b);this.tb(c);this.ub();this.sb();this.vb()}}function nb(){return 0<nb.i}var ob;
function pb(a){A[qb()>>2]=a}function rb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function H(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=rb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function tb(a){if("/"===a)return"/";a=H(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ub(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=rb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var vb=[];function wb(a,b){vb[a]={input:[],output:[],F:b};xb(a,yb)}
var yb={open:function(a){var b=vb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.F.flush(a.tty)},flush:function(a){a.tty.F.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.F.Ca)throw new I(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.F.Ca(a.tty)}catch(m){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.F.qa)throw new I(60);try{for(var e=
0;e<d;e++)a.tty.F.qa(a.tty,b[c+e])}catch(g){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},Ab={Ca:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.i?Buffer.i(256):new Buffer(256),d=0;try{d=oa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=zb(b,!0)}return a.input.shift()},qa:function(a,b){null===b||10===b?(ra(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(Ja(a.output,0)),a.output=[])}},Bb={qa:function(a,b){null===b||10===b?(l(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ja(a.output,0)),a.output=[])}},J={o:null,u:function(){return J.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.o||(J.o={dir:{node:{m:J.c.m,l:J.c.l,lookup:J.c.lookup,Y:J.c.Y,rename:J.c.rename,unlink:J.c.unlink,rmdir:J.c.rmdir,readdir:J.c.readdir,symlink:J.c.symlink},stream:{B:J.f.B}},file:{node:{m:J.c.m,l:J.c.l},stream:{B:J.f.B,read:J.f.read,write:J.f.write,sa:J.f.sa,Ja:J.f.Ja,$:J.f.$}},link:{node:{m:J.c.m,l:J.c.l,readlink:J.c.readlink},stream:{}},va:{node:{m:J.c.m,l:J.c.l},stream:Cb}});c=Db(a,b,c,d);K(c.mode)?(c.c=J.o.dir.node,
c.f=J.o.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=J.o.file.node,c.f=J.o.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=J.o.link.node,c.f=J.o.link.stream):8192===(c.mode&61440)&&(c.c=J.o.va.node,c.f=J.o.va.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Nb:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Ob:function(a){return a.b?a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array(0)},za:function(a,b){var c=a.b?a.b.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))},qb:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(b);c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{m:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.cb=4096;b.blocks=Math.ceil(b.size/b.cb);return b},l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.qb(a,b.size)},lookup:function(){throw Eb[44];},Y:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=
Fb(b,c)}catch(g){}if(d)for(var e in d.b)throw new I(55);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Fb(a,b),d;for(d in c.b)throw new I(55);delete a.b[b]},readdir:function(a){var b=[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},f:{read:function(a,b,c,d,e){var g=
a.node.b;if(e>=a.node.g)return 0;a=Math.min(a.node.g-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===z.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===e)return a.b=b.slice(c,c+d),a.g=d;if(e+d<=a.g)return a.b.set(b.subarray(c,c+d),e),d}J.za(a,e+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),e);else for(g=
0;g<d;g++)a.b[e+g]=b[c+g];a.g=Math.max(a.g,e+d);return d},B:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new I(28);return b},sa:function(a,b,c){J.za(a.node,b+c);a.node.g=Math.max(a.node.g,b+c)},Ja:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.b;if(g&2||a.buffer!==Qa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=Ha(g);c<
g;)z[b+c++]=0;c=b;if(!c)throw new I(48);z.set(a,c)}else d=!1,c=a.byteOffset;return{s:c,bb:d}},$:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;J.f.write(a,b,0,d,c,!1);return 0}}},Gb=null,Hb={},Ib=[],Jb=1,Kb=null,Lb=!0,Mb={},I=null,Eb={};
function L(a,b){a=ub("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Aa:!0,ra:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ra)throw new I(32);a=rb(a.split("/").filter(function(h){return!!h}),!1);var e=Gb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Fb(e,a[d]);c=H(c+"/"+a[d]);e.O&&(!g||g&&b.Aa)&&(e=e.O.root);if(!g||b.N)for(g=0;40960===(e.mode&61440);)if(e=Nb(c),c=ub(sb(c),e),e=L(c,{ra:b.ra}).node,40<g++)throw new I(32);}return{path:c,node:e}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.u.Ka,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Kb.length}function Fb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.c.lookup?0:2)throw new I(c,a);for(c=Kb[Pb(a.id,b)];c;c=c.D){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Db(a,b,c,d){a=new Rb(a,b,c,d);b=Pb(a.parent.id,a.name);a.D=Kb[b];return Kb[b]=a}function K(a){return 16384===(a&61440)}var Sb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Qb(a,b){if(Lb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ub(a,b){try{return Fb(a,b),20}catch(c){}return Qb(a,"wx")}function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Ib[a])return a;throw new I(33);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={});var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Ib[b]=a}
var Cb={open:function(a){a.f=Hb[a.node.rdev].f;a.f.open&&a.f.open(a)},B:function(){throw new I(70);}};function xb(a,b){Hb[a]={f:b}}function Yb(a,b){var c="/"===b,d=!b;if(c&&Gb)throw new I(10);if(!c&&!d){var e=L(b,{Aa:!1});b=e.path;e=e.node;if(e.O)throw new I(10);if(!K(e.mode))throw new I(54);}b={type:a,Yb:{},Ka:b,ob:[]};a=a.u(b);a.u=b;b.root=a;c?Gb=a:e&&(e.O=b,e.u&&e.u.ob.push(b))}
function Zb(a,b,c){var d=L(a,{parent:!0}).node;a=tb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Ub(d,a);if(e)throw new I(e);if(!d.c.Y)throw new I(63);return d.c.Y(d,a,b,c)}function M(a,b){return Zb(a,(void 0!==b?b:511)&1023|16384,0)}function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}
function ac(a,b){if(!ub(a))throw new I(44);var c=L(b,{parent:!0}).node;if(!c)throw new I(44);b=tb(b);var d=Ub(c,b);if(d)throw new I(d);if(!c.c.symlink)throw new I(63);return c.c.symlink(c,b,a)}
function bc(a){var b=L(a,{parent:!0}).node,c=tb(a),d=Fb(b,c);a:{try{var e=Fb(b,c)}catch(h){e=h.h;break a}var g=Qb(b,"wx");e=g?g:K(e.mode)?31:0}if(e)throw new I(e);if(!b.c.unlink)throw new I(63);if(d.O)throw new I(10);try{Mb.willDeletePath&&Mb.willDeletePath(a)}catch(h){l("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Pb(d.parent.id,d.name);if(Kb[b]===d)Kb[b]=d.D;else for(b=Kb[b];b;){if(b.D===d){b.D=d.D;break}b=b.D}try{if(Mb.onDeletePath)Mb.onDeletePath(a)}catch(h){l("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Nb(a){a=L(a).node;if(!a)throw new I(44);if(!a.c.readlink)throw new I(28);return ub(Ob(a.parent),a.c.readlink(a))}function cc(a,b){a=L(a,{N:!b}).node;if(!a)throw new I(44);if(!a.c.m)throw new I(63);return a.c.m(a)}function dc(a){return cc(a,!0)}function ec(a,b){var c;"string"===typeof a?c=L(a,{N:!0}).node:c=a;if(!c.c.l)throw new I(63);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function fc(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=H(a);try{g=L(a,{N:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(g){if(b&128)throw new I(20);}else g=Zb(a,c,0),e=!0;if(!g)throw new I(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!K(g.mode))throw new I(54);if(!e&&(c=g?40960===(g.mode&61440)?32:K(g.mode)&&
("r"!==Tb(b)||b&512)?31:Qb(g,Tb(b)):44))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=L(c,{N:!0}).node:h=c;if(!h.c.l)throw new I(63);if(K(h.mode))throw new I(31);if(32768!==(h.mode&61440))throw new I(28);if(c=Qb(h,"w"))throw new I(c);h.c.l(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Wb({node:g,path:Ob(g),flags:b,seekable:!0,position:0,f:g.f,Bb:[],error:!1},d);d.f.open&&d.f.open(d);!f.logReadFiles||b&1||(hc||(hc={}),a in hc||(hc[a]=1,l("FS.trackingDelegate error on read file: "+a)));try{Mb.onOpenFile&&
(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Mb.onOpenFile(a,g))}catch(m){l("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function ic(a){if(null===a.fd)throw new I(8);a.A&&(a.A=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Ib[a.fd]=null}a.fd=null}function jc(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.f.B)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.f.B(a,b,c);a.Bb=[];return a.position}
function kc(a,b,c,d){var e=z;if(0>c||0>d)throw new I(28);if(null===a.fd)throw new I(8);if(1===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.f.read)throw new I(28);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new I(70);b=a.f.read(a,e,b,c,d);g||(a.position+=b);return b}
function lc(a,b,c,d,e,g){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.f.write)throw new I(28);a.seekable&&a.flags&1024&&jc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I(70);b=a.f.write(a,b,c,d,e,g);h||(a.position+=b);try{if(a.path&&Mb.onWriteToFile)Mb.onWriteToFile(a.path)}catch(m){l("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function mc(){I||(I=function(a,b){this.node=b;this.rb=function(c){this.h=c};this.rb(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){Eb[a]=new I(a);Eb[a].stack="<generic error, no stack>"}))}var nc;function oc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function pc(a,b,c,d){a=H(("string"===typeof a?a:Ob(a))+"/"+b);return M(a,oc(c,d))}
function qc(a,b){a="string"===typeof a?a:Ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=H(a+"/"+c);try{M(d)}catch(e){}a=d}}return d}function rc(a,b,c,d){a=H(("string"===typeof a?a:Ob(a))+"/"+b);c=oc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}
function sc(a,b,c,d,e,g){a=b?H(("string"===typeof a?a:Ob(a))+"/"+b):a;d=oc(d,e);e=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}ec(e,d|146);a=fc(e,"w");lc(a,c,0,c.length,0,g);ic(a);ec(e,d)}return e}
function N(a,b,c,d){a=H(("string"===typeof a?a:Ob(a))+"/"+b);b=oc(!!c,!!d);N.Fa||(N.Fa=64);var e=N.Fa++<<8|0;xb(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,m,n){for(var v=0,t=0;t<n;t++){try{var u=c()}catch(w){throw new I(29);}if(void 0===u&&0===v)throw new I(6);if(null===u||void 0===u)break;v++;h[m+t]=u}v&&(g.node.timestamp=Date.now());return v},write:function(g,h,m,n){for(var v=0;v<n;v++)try{d(h[m+v])}catch(t){throw new I(29);}n&&(g.node.timestamp=
Date.now());return v}});return $b(a,b,e)}function tc(a,b,c){a=H(("string"===typeof a?a:Ob(a))+"/"+b);return ac(c,a)}
function uc(a){if(a.mb||a.nb||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.b=zb(la(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||pb(29);return b}
function vc(a,b,c,d,e){function g(){this.pa=!1;this.i=[]}g.prototype.get=function(t){if(!(t>this.length-1||0>t)){var u=t%this.chunkSize;return this.Da(t/this.chunkSize|0)[u]}};g.prototype.ha=function(t){this.Da=t};g.prototype.ta=function(){var t=new XMLHttpRequest;t.open("HEAD",c,!1);t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);var u=Number(t.getResponseHeader("Content-length")),w,k=(w=t.getResponseHeader("Accept-Ranges"))&&"bytes"===
w;t=(w=t.getResponseHeader("Content-Encoding"))&&"gzip"===w;var x=1048576;k||(x=u);var y=this;y.ha(function(E){var ja=E*x,La=(E+1)*x-1;La=Math.min(La,u-1);if("undefined"===typeof y.i[E]){var ze=y.i;if(ja>La)throw Error("invalid range ("+ja+", "+La+") or no bytes requested!");if(La>u-1)throw Error("only "+u+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);u!==x&&R.setRequestHeader("Range","bytes="+ja+"-"+La);"undefined"!=typeof Uint8Array&&(R.responseType="arraybuffer");
R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);ja=void 0!==R.response?new Uint8Array(R.response||[]):zb(R.responseText||"",!0);ze[E]=ja}if("undefined"===typeof y.i[E])throw Error("doXHR failed!");return y.i[E]});if(t||!u)x=u=1,x=u=this.Da(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.$a=u;this.Za=x;this.pa=
!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.pa||this.ta();return this.$a}},chunkSize:{get:function(){this.pa||this.ta();return this.Za}}});var m=void 0}else m=c,h=void 0;var n=rc(a,b,d,e);h?n.b=h:m&&(n.b=null,n.url=m);Object.defineProperties(n,{g:{get:function(){return this.b.length}}});var v={};Object.keys(n.f).forEach(function(t){var u=
n.f[t];v[t]=function(){if(!uc(n))throw new I(29);return u.apply(null,arguments)}});v.read=function(t,u,w,k,x){if(!uc(n))throw new I(29);t=t.node.b;if(x>=t.length)return 0;k=Math.min(t.length-x,k);if(t.slice)for(var y=0;y<k;y++)u[w+y]=t[x+y];else for(y=0;y<k;y++)u[w+y]=t.get(x+y);return k};n.f=v;return n}
function wc(a,b,c,d,e,g,h,m,n,v){function t(k){function x(E){v&&v();m||sc(a,b,E,d,e,n);g&&g();db(w)}var y=!1;f.preloadPlugins.forEach(function(E){!y&&E.canHandle(u)&&(E.handle(k,u,x,function(){h&&h();db(w)}),y=!0)});y||x(k)}xc();var u=b?ub(H(a+"/"+b)):a,w="cp "+u;cb(w);"string"==typeof c?yc(c,function(k){t(k)},h):t(c)}var O={},Xb,hc,zc={};
function Ac(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&H(b)!==H(Ob(e.node)))return-54;throw e;}A[c>>2]=d.dev;A[c+4>>2]=0;A[c+8>>2]=d.ino;A[c+12>>2]=d.mode;A[c+16>>2]=d.nlink;A[c+20>>2]=d.uid;A[c+24>>2]=d.gid;A[c+28>>2]=d.rdev;A[c+32>>2]=0;B=[d.size>>>0,(C=d.size,1<=+ya(C)?0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+40>>2]=B[0];A[c+44>>2]=B[1];A[c+48>>2]=4096;A[c+52>>2]=d.blocks;A[c+56>>2]=d.atime.getTime()/1E3|0;A[c+60>>2]=0;A[c+64>>2]=d.mtime.getTime()/
1E3|0;A[c+68>>2]=0;A[c+72>>2]=d.ctime.getTime()/1E3|0;A[c+76>>2]=0;B=[d.ino>>>0,(C=d.ino,1<=+ya(C)?0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+80>>2]=B[0];A[c+84>>2]=B[1];return 0}var Bc=void 0;function Cc(){Bc+=4;return A[Bc-4>>2]}function P(a){a=Ib[a];if(!a)throw new I(8);return a}var Dc;ia?Dc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Dc=dateNow:Dc=function(){return performance.now()};
var Ec=null,Fc=0,Gc=null,Hc=0,Ic=0,Jc=0,Kc=0,Lc=[],Mc={},Nc,Oc,Pc,Qc=!1,Rc=!1,Sc=[];
function xc(){function a(){Rc=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Tc){Tc=!0;try{Uc=!0}catch(c){Uc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Vc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Uc?null:console.log("warning: no BlobBuilder");
Wc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.La||"undefined"!==typeof Wc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.La=!0);f.preloadPlugins.push({canHandle:function(c){return!f.La&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(Uc)try{h=new Blob([c],{type:Xc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Xc(d)}))}catch(v){ta("Blob constructor present but fails: "+
v+"; falling back to blob builder")}h||(h=new Vc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=Wc.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var v=document.createElement("canvas");v.width=n.width;v.height=n.height;v.getContext("2d").drawImage(n,0,0);f.preloadedImages[d]=v;Wc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Xb&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(u){n||(n=!0,f.preloadedAudios[d]=u,e&&e(c))}function m(){n||(n=!0,f.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(Uc){try{var v=new Blob([c],{type:Xc(d)})}catch(u){return m()}v=Wc.createObjectURL(v);var t=new Audio;t.addEventListener("canplaythrough",function(){h(t)},!1);t.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,k=0,
x=0;x<c.length;x++)for(w=w<<8|c[x],k+=8;6<=k;){var y=w>>k-6&63;k-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[y]}2==k?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==k&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+u;h(t)}};t.src=v;Yc(function(){h(t)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!Rc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Zc(a,b,c,d){if(b&&f.K&&a==f.canvas)return f.K;var e;if(b){var g={antialias:!1,alpha:!1,Ga:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof $c&&(e=ad(a,g)))var m=bd[e].S}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof Q,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.K=m,b&&(S=bd[e],f.K=Q=S&&S.S),f.bc=b,Sc.forEach(function(n){n()}),xc());return m}var cd=!1,dd=void 0,ed=void 0;
function fd(a,b){function c(){Qc=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=gd,dd&&d.requestPointerLock(),Qc=!0,ed?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Sa[SDL.screen>>2]|8388608),hd(f.canvas),id()):hd(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),ed?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Sa[SDL.screen>>2]&
-8388609),hd(f.canvas),id()):hd(d));if(f.onFullScreen)f.onFullScreen(Qc);if(f.onFullscreen)f.onFullscreen(Qc)}dd=a;ed=b;"undefined"===typeof dd&&(dd=!0);"undefined"===typeof ed&&(ed=!1);var d=f.canvas;cd||(cd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function gd(){if(!Qc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var jd=0;function kd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jd)jd=b+1E3/60;else for(;b+2>=jd;)jd+=1E3/60;setTimeout(a,Math.max(jd-b,0))}}function Yc(a){noExitRuntime=!0;setTimeout(function(){Fa||a()},1E4)}
function Xc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ld=0,md=0,nd=0,od=0;
function pd(a){if(Rc)"mousemove"!=a.type&&"mozMovementX"in a?nd=od=0:(nd=a.movementX||a.mozMovementX||a.webkitMovementX||0,od=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ld=SDL.Ub+nd,md=SDL.Vb+od):(ld+=nd,md+=od);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,nd=e-ld,od=a-md,ld=e,md=a)}}function yc(a,b,c){var d="al "+a;ma(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&db(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&cb(d)}var qd=[];function id(){var a=f.canvas;qd.forEach(function(b){b(a.width,a.height)})}function rd(a,b,c){hd(f.canvas,a,b);c||id()}
function hd(a,b,c){b&&c?(a.Cb=b,a.ib=c):(b=a.Cb,c=a.ib);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}ed?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Tc,Uc,Vc,Wc;
function sd(a,b){Ic=a;Jc=b;if(Gc)if(0==a)Ec=function(){var d=Math.max(0,Oc+b-Dc())|0;setTimeout(Pc,d)};else if(1==a)Ec=function(){kd(Pc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Ec=function(){setImmediate(Pc)}}}
function td(a,b,c,d,e){noExitRuntime=!0;assert(!Gc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Gc=a;Hc=d;var g=Fc;Pc=function(){if(!Fa)if(0<Lc.length){var h=Date.now(),m=Lc.shift();m.Ba(m.T);if(Nc){var n=Nc,v=0==n%1?n-1:Math.floor(n);Nc=m.Ib?v:(8*n+(v+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||
"Please wait...",m=Nc,n=Mc.Lb,m?m<n?f.setStatus(h+" ("+(n-m)+"/"+n+")"):f.setStatus(h):f.setStatus(""));g<Fc||setTimeout(Pc,0)}else if(!(g<Fc))if(Kc=Kc+1|0,1==Ic&&1<Jc&&0!=Kc%Jc)Ec();else{0==Ic&&(Oc=Dc());if(S)for(h=S.H,S.H=S.P,S.P=h,h=S.v,S.v=S.da,S.da=h,h=0;21>=h;++h)S.v[h]=0;a:if(!(Fa||f.preMainLoop&&!1===f.preMainLoop())){try{a()}catch(t){if(t instanceof qa||"unwind"==t)break a;t&&"object"===typeof t&&t.stack&&l("exception thrown: "+[t,t.stack]);throw t;}f.postMainLoop&&f.postMainLoop()}g<Fc||
("object"===typeof SDL&&SDL.audio&&SDL.audio.pb&&SDL.audio.pb(),Ec())}};e||(b&&0<b?sd(0,1E3/b):sd(1,1),Ec());if(c)throw"unwind";}var ud={};function vd(){if(!wd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in ud)a[b]=ud[b];var c=[];for(b in a)c.push(b+"="+a[b]);wd=c}return wd}
var wd,xd=1,yd=[],zd={},T=[],Ad=[],Bd=[],Cd=[],U=[],Dd=[],bd=[],Ed=[],Fd=[1,1,2,2,4,4,4,2,3,4,8],Gd={},Hd={};function V(a){Id||(Id=a)}function Jd(a){for(var b=xd++,c=a.length;c<b;c++)a[c]=null;return b}
function Kd(a){Ld=!1;for(var b=0;b<S.Ia;++b){var c=S.U[b];if(c.ia&&c.enabled){Ld=!0;var d=c.ba;d=0<d?a*d:c.size*Fd[c.type-5120]*a;var e=32-Math.clz32(d-1);var g=S.H[e],h=S.v[e];S.v[e]=S.v[e]+1&63;var m=g[h];m?e=m:(m=Q.getParameter(34964),g[h]=Q.createBuffer(),Q.bindBuffer(34962,g[h]),Q.bufferData(34962,1<<e,35048),Q.bindBuffer(34962,m),e=g[h]);Q.bindBuffer(34962,e);Q.bufferSubData(34962,0,F.subarray(c.s,c.s+d));Md(c.size,c.type,c.ba,0);c.Va.call(Q,b,c.size,c.type,c.Ma,c.ba,0)}}}
function W(a,b,c,d){0!=b&&(null===a[b]?console.error(c+" called with an already deleted "+d+" ID "+b+"!"):a[b]||console.error(c+" called with an invalid "+d+" ID "+b+"!"))}
function Md(a,b,c,d){var e=1;switch(b){case 5120:case 5121:e=1;break;case 5122:case 5123:e=2;break;case 5124:case 5125:case 5126:e=4;break;case 5130:e=8;break;default:if(2<=S.version)if(33640==b||36255==b){e=4;break}else if(5131==b){e=2;break}console.error("Invalid vertex attribute data type GLenum "+b+" passed to GL function!")}32993==a?console.error("WebGL does not support size=GL_BGRA in a call to glVertexAttribPointer! Please use size=4 and type=GL_UNSIGNED_BYTE instead!"):(1>a||4<a)&&console.error("Invalid dimension="+
a+" in call to glVertexAttribPointer, must be 1,2,3 or 4.");(0>c||255<c)&&console.error("Invalid stride="+c+" in call to glVertexAttribPointer. Note that maximum supported stride in WebGL is 255!");0!=d%e&&console.error("GL spec section 6.4 error: vertex attribute data offset of "+d+" bytes should have been a multiple of the data type size that was used: GLenum "+b+" has size of "+e+" bytes!");0!=c%e&&console.error("GL spec section 6.4 error: vertex attribute data stride of "+c+" bytes should have been a multiple of the data type size that was used: GLenum "+
b+" has size of "+e+" bytes!")}
function ad(a,b){var c=1<b.Ga?a.getContext("webgl2",b):a.getContext("webgl",b);if(c){a=Jd(bd);var d={Pb:a,attributes:b,version:b.Ga,S:c};c.canvas&&(c.canvas.Db=d);bd[a]=d;("undefined"===typeof b.fb||b.fb)&&Nd(d);d.Ia=d.S.getParameter(34921);d.U=[];for(b=0;b<d.Ia;b++)d.U[b]={enabled:!1,ia:!1,size:0,type:0,Ma:0,ba:0,s:0,Va:null};d.v=[];d.da=[];d.v.length=d.da.length=22;d.H=[];d.P=[];d.H.length=d.P.length=22;d.G=[];d.G.length=22;for(b=0;21>=b;++b){d.G[b]=null;d.v[b]=d.da[b]=0;d.H[b]=[];d.P[b]=[];c=d.H[b];
var e=d.P[b];c.length=e.length=64;for(var g=0;64>g;++g)c[g]=e[g]=null}}else a=0;return a}
function Nd(a){a||(a=S);if(!a.kb){a.kb=!0;var b=a.S;b.Jb=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Kb=b.getExtension("EXT_disjoint_timer_query");b.Wb=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var $c={},Id,S,Ld;function Od(a,b,c,d,e){for(var g=0;g<a;g++){var h=Q[c](),m=h&&Jd(d);h?(h.name=m,d[m]=h):(V(1282),l("GL_INVALID_OPERATION in "+e+": GLctx."+c+" returned null - most likely GL context is lost!"));A[b+4*g>>2]=m}}
function Pd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}c=2*(Q.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);l("GL_INVALID_ENUM in glGet0v("+a+") on a name which returns a string!");
return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:V(1280);l("GL_INVALID_ENUM in glGet0v("+a+") and it returns null!");return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)A[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}A[b>>2]=c}else l("GL_INVALID_VALUE in glGet0v(name="+a+": Function called with null out pointer!"),V(1281)}function Qd(a){var b=Ma(a)+1,c=Ha(b);Ka(a,F,c,b);return c}
function Rd(a){switch(a){case 34962:a=34964;break;case 34963:a=34965;break;case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=Q.getParameter(a))?a.name|0:0}function Sd(a){switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}}
function Td(a){a-=5120;if(0==a)return z;if(1==a)return F;if(2==a)return xa;if(4==a)return A;if(6==a)return Ca;if(5==a||28922==a||28520==a||30779==a||30782==a)return Sa;3!=a&&11!=a&&27699!=a&&27700!=a&&28515!=a&&31073!=a&&l("Invalid WebGL type 0x"+(a+5120).toString()+" passed to $heapObjectForWebGLType!");return Ra}
function Ud(a,b,c,d,e){a=Td(a);var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=1<<g,m={5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4};m[b-6402]||6402==b||6406==b||6409==b||6403==b||36244==b||l("Invalid format=0x"+b.toString(16)+" passed to function _colorChannelsInGlTextureFormat()!");b=c*(m[b-6402]||1)*h;assert(!0,"Unpack alignment must be a power of 2! (Allowed values per WebGL spec are 1, 2, 4 or 8)");d*=b+4-1&-4;assert(e>>g<<g==e,"Pointer to texture data passed to texture get function must be aligned to the byte size of the pixel type!");
return a.subarray(e>>g,e+d>>g)}function Vd(a,b,c,d){this.id=a;this.y=this.x=0;this.na=!1;this.Sa=this.Ra=0;this.width=b;this.height=c;this.Qa=b;this.Pa=c;this.title=d;this.attributes=Wd;this.buttons=0;this.keys=[];this.ka=[];this.Oa=0;this.Ua=this.ua=this.Ea=this.la=this.aa=this.V=this.ya=this.Z=this.W=this.Xa=this.Wa=this.J=this.Ya=this.title=null}function X(a){return 0>=a||!Y?null:Y[a-1]}
var Xd=null,Z=null,Y=null,Wd=null,Yd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Zd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function $d(){var a=Z,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ae(a){Z&&Z.ua&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||D.get(Z.ua)(Z.id,a))}
function be(a,b){if(Z){var c=Zd(a);if(-1!=c){var d=b&&Z.keys[c];Z.keys[c]=b;Z.ka[a]=b;Z.Ea&&(d&&(b=2),D.get(Z.Ea)(Z.id,c,a,b,$d()))}}}function ce(){de()}function ee(){de()}function fe(a){be(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ge(a){be(a.keyCode,0)}function he(){if(Z)for(var a=0;a<Z.ka.length;++a)Z.ka[a]&&be(a,0)}function ie(a){Z&&(pd(a),a.target==f.canvas&&Z.ya&&D.get(Z.ya)(Z.id,ld,md))}function je(a){Z&&a.target==f.canvas&&Z.V&&D.get(Z.V)(Z.id,1)}
function ke(a){Z&&a.target==f.canvas&&Z.V&&D.get(Z.V)(Z.id,0)}function le(a,b){if(Z&&(pd(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Z.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Z.buttons&=~(1<<c);Z.Z&&D.get(Z.Z)(Z.id,c,b,$d())}}function me(a){Z&&le(a,1)}function ne(a){Z&&le(a,0)}
function oe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Z&&Z.aa&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;D.get(Z.aa)(Z.id,b,c);a.preventDefault()}}var pe={},qe=null,re=null;
function de(){if(Kc!==re||!Kc){qe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;re=Kc;for(var a=0;a<qe.length;++a){var b=qe[a];if(b){pe[a]||(console.log("glfw joystick connected:",a),pe[a]={id:Ga(zb(b.id),"i8"),Hb:b.buttons.length,Gb:b.axes.length,buttons:Ga(Array(b.buttons.length),"i8"),axes:Ga(Array(4*b.axes.length),"float")});for(var c=pe[a],d=0;d<b.buttons.length;++d)r(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)r(c.axes+
4*d,b.axes[d],"float")}else pe[a]&&(console.log("glfw joystick disconnected",a),se(pe[a].id),se(pe[a].buttons),se(pe[a].axes),delete pe[a])}}}
function te(a){function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),v=new FileReader;v.onloadend=function(u){if(2!=v.readyState)++g,console.log("failed to read dropped file: "+m.name+": "+v.error);else{var w=new Uint8Array(u.target.result);var k=k||{};k.flags=k.flags||"w";u=fc(n,k.flags,k.mode);if("string"===typeof w){var x=new Uint8Array(Ma(w)+1);w=Ka(w,x,0,x.length);lc(u,x,0,w,void 0,k.eb)}else if(ArrayBuffer.isView(w))lc(u,w,0,w.byteLength,void 0,k.eb);else throw Error("Unsupported data type");
ic(u);if(++g===e){D.get(Z.la)(Z.id,e,c);for(k=0;k<d.length;++k)se(d[k]);se(c)}}};v.readAsArrayBuffer(m);var t=Ga(zb(n),"i8");d.push(t);r(c+4*h,t,"i8*")}if(Z&&Z.la&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ga(Array(4*a.dataTransfer.files.length),"i8*"),d=[],e=a.dataTransfer.files.length,g=0;qc("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function ue(a){if(Z&&Z.la)return a.preventDefault(),!1}
function ve(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}if(!we){we=!0;A[xe()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);A[ye()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),e=a(b);d=Na(d);e=Na(e);b.getTimezoneOffset()<c.getTimezoneOffset()?(A[Ae()>>2]=d,A[Ae()+4>>2]=e):(A[Ae()>>2]=e,A[Ae()+4>>2]=d)}}var we;
function Be(a){switch(a){case 0:return 32E3;case 1:case 2:case 3:return 255;case 4:case 5:case 16:case 17:case 18:return 4096;case 6:case 7:case 20:return 1;case 8:return 0;case 9:case 10:case 11:case 12:case 14:case 15:case 19:return-1;case 13:return 64}pb(28);return-1}function Ce(a){return 0===a%4&&(0!==a%100||0===a%400)}function De(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ee=[31,29,31,30,31,30,31,31,30,31,30,31],Fe=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ge(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ce(a.getFullYear())?Ee:Fe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function He(a,b,c,d){function e(k,x,y){for(k="number"===typeof k?k.toString():k||"";k.length<x;)k=y[0]+k;return k}function g(k,x){return e(k,x,"0")}function h(k,x){function y(ja){return 0>ja?-1:0<ja?1:0}var E;0===(E=y(k.getFullYear()-x.getFullYear()))&&0===(E=y(k.getMonth()-x.getMonth()))&&(E=y(k.getDate()-x.getDate()));return E}function m(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function n(k){k=Ge(new Date(k.j+1900,0,1),k.ga);var x=new Date(k.getFullYear()+1,0,4),y=m(new Date(k.getFullYear(),0,4));x=m(x);return 0>=h(y,k)?0>=h(x,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var v=A[d+40>>2];d={zb:A[d>>2],yb:A[d+4>>2],ea:A[d+8>>2],R:A[d+12>>2],I:A[d+16>>2],j:A[d+20>>2],fa:A[d+24>>2],ga:A[d+28>>2],ac:A[d+32>>2],xb:A[d+36>>
2],Ab:v?G(v):""};c=G(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in v)c=c.replace(new RegExp(t,"g"),v[t]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");v={"%a":function(k){return u[k.fa].substring(0,3)},"%A":function(k){return u[k.fa]},"%b":function(k){return w[k.I].substring(0,3)},"%B":function(k){return w[k.I]},"%C":function(k){return g((k.j+1900)/100|0,2)},"%d":function(k){return g(k.R,2)},"%e":function(k){return e(k.R,2," ")},"%g":function(k){return n(k).toString().substring(2)},"%G":function(k){return n(k)},"%H":function(k){return g(k.ea,2)},
"%I":function(k){k=k.ea;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.R+De(Ce(k.j+1900)?Ee:Fe,k.I-1),3)},"%m":function(k){return g(k.I+1,2)},"%M":function(k){return g(k.yb,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ea&&12>k.ea?"AM":"PM"},"%S":function(k){return g(k.zb,2)},"%t":function(){return"\t"},"%u":function(k){return k.fa||7},"%U":function(k){var x=new Date(k.j+1900,0,1),y=0===x.getDay()?x:Ge(x,7-x.getDay());k=new Date(k.j+1900,k.I,k.R);return 0>h(y,k)?
g(Math.ceil((31-y.getDate()+(De(Ce(k.getFullYear())?Ee:Fe,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(y,x)?"01":"00"},"%V":function(k){var x=new Date(k.j+1901,0,4),y=m(new Date(k.j+1900,0,4));x=m(x);var E=Ge(new Date(k.j+1900,0,1),k.ga);return 0>h(E,y)?"53":0>=h(x,E)?"01":g(Math.ceil((y.getFullYear()<k.j+1900?k.ga+32-y.getDate():k.ga+1-y.getDate())/7),2)},"%w":function(k){return k.fa},"%W":function(k){var x=new Date(k.j,0,1),y=1===x.getDay()?x:Ge(x,0===x.getDay()?1:7-x.getDay()+1);k=new Date(k.j+
1900,k.I,k.R);return 0>h(y,k)?g(Math.ceil((31-y.getDate()+(De(Ce(k.getFullYear())?Ee:Fe,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(y,x)?"01":"00"},"%y":function(k){return(k.j+1900).toString().substring(2)},"%Y":function(k){return k.j+1900},"%z":function(k){k=k.xb;var x=0<=k;k=Math.abs(k)/60;return(x?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Ab},"%%":function(){return"%"}};for(t in v)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),v[t](d)));t=zb(c,!1);if(t.length>
b)return 0;z.set(t,a);return t.length-1}function Rb(a,b,c,d){a||(a=this);this.parent=a;this.u=a.u;this.O=null;this.id=Jb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d}
Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},nb:{get:function(){return K(this.mode)}},mb:{get:function(){return 8192===(this.mode&61440)}}});mc();Kb=Array(4096);Yb(J,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");xb(259,{read:function(){return 0},write:function(d,e,g,h){return h}});$b("/dev/null",259);wb(1280,Ab);wb(1536,Bb);$b("/dev/tty",1280);$b("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ia)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});N("/dev","random",b);N("/dev","urandom",b);
M("/dev/shm");M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");Yb({u:function(){var a=Db("/proc/self","fd",16895,73);a.c={lookup:function(b,c){var d=Ib[+c];if(!d)throw new I(8);b={parent:null,u:{Ka:"fake"},c:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");f.FS_createFolder=pc;f.FS_createPath=qc;f.FS_createDataFile=sc;f.FS_createPreloadedFile=wc;f.FS_createLazyFile=vc;f.FS_createLink=tc;f.FS_createDevice=N;f.FS_unlink=bc;
f.requestFullscreen=function(a,b){fd(a,b)};f.requestAnimationFrame=function(a){kd(a)};f.setCanvasSize=function(a,b,c){rd(a,b,c)};f.pauseMainLoop=function(){Ec=null;Fc++};f.resumeMainLoop=function(){Fc++;var a=Ic,b=Jc,c=Gc;Gc=null;td(c,0,!1,Hc,!0);sd(a,b);Ec()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Zc(a,b,c,d)};var Q;
function zb(a,b){var c=Array(Ma(a)+1);a=Ka(a,c,0,c.length);b&&(c.length=a);return c}
var Qe={__cxa_allocate_exception:function(a){return Ha(a+16)+16},__cxa_atexit:function(){},__cxa_throw:function(a,b,c){(new mb(a)).jb(b,c);"uncaught_exception"in nb?nb.i++:nb.i=1;throw a;},__gmtime_r:function(a,b){a=new Date(1E3*A[a>>2]);A[b>>2]=a.getUTCSeconds();A[b+4>>2]=a.getUTCMinutes();A[b+8>>2]=a.getUTCHours();A[b+12>>2]=a.getUTCDate();A[b+16>>2]=a.getUTCMonth();A[b+20>>2]=a.getUTCFullYear()-1900;A[b+24>>2]=a.getUTCDay();A[b+36>>2]=0;A[b+32>>2]=0;A[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0;ob||(ob=Na("GMT"));A[b+40>>2]=ob;return b},__indirect_function_table:D,__map_file:function(){pb(63);return-1},__sys_fcntl64:function(a,b,c){Bc=c;try{var d=P(a);switch(b){case 0:var e=Cc();return 0>e?-28:fc(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Cc(),d.flags|=e,0;case 12:return e=Cc(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return pb(28),-1;default:return-28}}catch(g){return"undefined"!==typeof O&&g instanceof
I||q(g),-g.h}},__sys_fstat64:function(a,b){try{var c=P(a);return Ac(cc,c.path,b)}catch(d){return"undefined"!==typeof O&&d instanceof I||q(d),-d.h}},__sys_getcwd:function(a,b){try{if(0===b)return-28;if(b<Ma("/")+1)return-68;Ka("/",F,a,b);return a}catch(c){return"undefined"!==typeof O&&c instanceof I||q(c),-c.h}},__sys_getdents64:function(a,b,c){try{var d=P(a);if(!d.A){var e=L(d.path,{N:!0}).node;if(!e.c.readdir)throw new I(54);var g=e.c.readdir(e);d.A=g}a=0;for(var h=jc(d,0,1),m=Math.floor(h/280);m<
d.A.length&&a+280<=c;){var n=d.A[m];if("."===n[0]){var v=1;var t=4}else{var u=Fb(d.node,n);v=u.id;t=8192===(u.mode&61440)?2:K(u.mode)?4:40960===(u.mode&61440)?10:8}B=[v>>>0,(C=v,1<=+ya(C)?0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a>>2]=B[0];A[b+a+4>>2]=B[1];B=[280*(m+1)>>>0,(C=280*(m+1),1<=+ya(C)?0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a+8>>2]=B[0];A[b+a+12>>2]=B[1];xa[b+a+16>>1]=280;z[b+a+18>>0]=t;Ka(n,
F,b+a+19,256);a+=280;m+=1}jc(d,280*m,0);return a}catch(w){return"undefined"!==typeof O&&w instanceof I||q(w),-w.h}},__sys_ioctl:function(a,b,c){Bc=c;try{var d=P(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Cc();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Cc();if(!d.f.lb)throw new I(59);return d.f.lb(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?
0:-59;default:q("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof O&&g instanceof I||q(g),-g.h}},__sys_lstat64:function(a,b){try{return a=G(a),Ac(dc,a,b)}catch(c){return"undefined"!==typeof O&&c instanceof I||q(c),-c.h}},__sys_mkdir:function(a,b){try{return a=G(a),a=H(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),M(a,b),0}catch(c){return"undefined"!==typeof O&&c instanceof I||q(c),-c.h}},__sys_munmap:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=zc[a];if(d&&b===d.Qb){var e=
Ib[d.fd];if(d.$b&2){var g=d.flags,h=d.offset,m=F.slice(a,a+b);e&&e.f.$&&e.f.$(e,m,h,b,g)}zc[a]=null;d.bb&&se(d.Rb)}c=0}return c}catch(n){return"undefined"!==typeof O&&n instanceof I||q(n),-n.h}},__sys_open:function(a,b,c){Bc=c;try{var d=G(a),e=Cc();return fc(d,b,e).fd}catch(g){return"undefined"!==typeof O&&g instanceof I||q(g),-g.h}},__sys_read:function(a,b,c){try{var d=P(a);return kc(d,b,c)}catch(e){return"undefined"!==typeof O&&e instanceof I||q(e),-e.h}},__sys_readlink:function(a,b,c){try{a=G(a);
if(0>=c)var d=-28;else{var e=Nb(a),g=Math.min(c,Ma(e)),h=z[b+g];Ka(e,F,b,c+1);z[b+g]=h;d=g}return d}catch(m){return"undefined"!==typeof O&&m instanceof I||q(m),-m.h}},__sys_stat64:function(a,b){try{return a=G(a),Ac(cc,a,b)}catch(c){return"undefined"!==typeof O&&c instanceof I||q(c),-c.h}},abort:function(){q()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Dc();else return pb(28),-1;A[b>>2]=a/1E3|0;A[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_longjmp:function(a,b){Ie(a,b||
1);throw"longjmp";},emscripten_memcpy_big:function(a,b,c){F.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){a>>>=0;var b=F.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Ea.grow(Math.min(2147483648,d)-Qa.byteLength+65535>>>16);Ta(Ea.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},emscripten_set_main_loop_arg:function(a,b,c,d){td(function(){D.get(a)(b)},c,d,b)},
environ_get:function(a,b){var c=0;vd().forEach(function(d,e){var g=b+c;e=A[a+4*e>>2]=g;for(g=0;g<d.length;++g)z[e++>>0]=d.charCodeAt(g);z[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=vd();A[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0},fd_close:function(a){try{var b=P(a);ic(b);return 0}catch(c){return"undefined"!==typeof O&&c instanceof I||q(c),c.h}},fd_fdstat_get:function(a,b){try{var c=P(a);z[b>>0]=c.tty?2:K(c.mode)?3:40960===(c.mode&
61440)?7:4;return 0}catch(d){return"undefined"!==typeof O&&d instanceof I||q(d),d.h}},fd_read:function(a,b,c,d){try{a:{for(var e=P(a),g=a=0;g<c;g++){var h=A[b+(8*g+4)>>2],m=kc(e,A[b+8*g>>2],h,void 0);if(0>m){var n=-1;break a}a+=m;if(m<h)break}n=a}A[d>>2]=n;return 0}catch(v){return"undefined"!==typeof O&&v instanceof I||q(v),v.h}},fd_seek:function(a,b,c,d,e){try{var g=P(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;jc(g,a,d);B=[g.position>>>0,(C=g.position,1<=+ya(C)?
0<C?(za(+Aa(C/4294967296),4294967295)|0)>>>0:~~+Ba((C-+(~~C>>>0))/4294967296)>>>0:0)];A[e>>2]=B[0];A[e+4>>2]=B[1];g.A&&0===a&&0===d&&(g.A=null);return 0}catch(h){return"undefined"!==typeof O&&h instanceof I||q(h),h.h}},fd_write:function(a,b,c,d){try{a:{for(var e=P(a),g=a=0;g<c;g++){var h=lc(e,z,A[b+8*g>>2],A[b+(8*g+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}A[d>>2]=m;return 0}catch(n){return"undefined"!==typeof O&&n instanceof I||q(n),n.h}},getTempRet0:function(){return va|0},gettimeofday:function(a){var b=
Date.now();A[a>>2]=b/1E3|0;A[a+4>>2]=b%1E3*1E3|0;return 0},glActiveTexture:function(a){Q.activeTexture(a)},glAttachShader:function(a,b){W(T,a,"glAttachShader","program");W(U,b,"glAttachShader","shader");Q.attachShader(T[a],U[b])},glBindBuffer:function(a,b){W(yd,b,"glBindBuffer","buffer");34962==a?Q.L=b:34963==a&&(Q.M=b);35051==a?Q.wa=b:35052==a&&(Q.ja=b);Q.bindBuffer(a,yd[b])},glBindBufferBase:function(a,b,c){W(yd,c,"glBindBufferBase","buffer");Q.bindBufferBase(a,b,yd[c])},glBindFramebuffer:function(a,
b){W(Ad,b,"glBindFramebuffer","framebuffer");Q.bindFramebuffer(a,Ad[b])},glBindSampler:function(a,b){W(Ed,b,"glBindSampler","sampler");Q.bindSampler(a,Ed[b])},glBindTexture:function(a,b){W(Bd,b,"glBindTexture","texture");Q.bindTexture(a,Bd[b])},glBindVertexArray:function(a){assert(Q.bindVertexArray,"Must have WebGL2 or OES_vertex_array_object to use vao");Q.bindVertexArray(Dd[a]);a=Q.getParameter(34965);Q.M=a?a.name|0:0},glBlitFramebuffer:function(a,b,c,d,e,g,h,m,n,v){Q.blitFramebuffer(a,b,c,d,e,
g,h,m,n,v)},glBufferData:function(a,b,c,d){2<=S.version?c?Q.bufferData(a,F,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?F.subarray(c,c+b):b,d)},glCheckFramebufferStatus:function(a){return Q.checkFramebufferStatus(a)},glClear:function(a){Q.clear(a)},glClearColor:function(a,b,c,d){Q.clearColor(a,b,c,d)},glCompileShader:function(a){W(U,a,"glCompileShader","shader");Q.compileShader(U[a])},glCreateProgram:function(){var a=Jd(T),b=Q.createProgram();b.name=a;T[a]=b;return a},glCreateShader:function(a){var b=
Jd(U);U[b]=Q.createShader(a);return b},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=yd[d];e&&(Q.deleteBuffer(e),e.name=0,yd[d]=null,d==Q.L&&(Q.L=0),d==Q.M&&(Q.M=0),d==Q.wa&&(Q.wa=0),d==Q.ja&&(Q.ja=0))}},glDeleteFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=Ad[d];e&&(Q.deleteFramebuffer(e),e.name=0,Ad[d]=null)}},glDeleteProgram:function(a){if(a){var b=T[a];b?(Q.deleteProgram(b),b.name=0,T[a]=null,Gd[a]=null):V(1281)}},glDeleteSamplers:function(a,b){for(var c=
0;c<a;c++){var d=A[b+4*c>>2],e=Ed[d];e&&(Q.deleteSampler(e),e.name=0,Ed[d]=null)}},glDeleteShader:function(a){if(a){var b=U[a];b?(Q.deleteShader(b),U[a]=null):V(1281)}},glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Bd[d];e&&(Q.deleteTexture(e),e.name=0,Bd[d]=null)}},glDeleteVertexArrays:function(a,b){assert(Q.deleteVertexArray,"Must have WebGL2 or OES_vertex_array_object to use vao");for(var c=0;c<a;c++){var d=A[b+4*c>>2];Q.deleteVertexArray(Dd[d]);Dd[d]=null}},glDetachShader:function(a,
b){W(T,a,"glDetachShader","program");W(U,b,"glDetachShader","shader");Q.detachShader(T[a],U[b])},glDrawArrays:function(a,b,c){Kd(b+c);Q.drawArrays(a,b,c);Ld&&Q.bindBuffer(34962,yd[Q.L])},glDrawElements:function(a,b,c,d){if(!Q.M){var e=1*Fd[c-5120]*b;var g=32-Math.clz32(e-1);var h=S.G[g];h?g=h:(h=Q.getParameter(34965),S.G[g]=Q.createBuffer(),Q.bindBuffer(34963,S.G[g]),Q.bufferData(34963,1<<g,35048),Q.bindBuffer(34963,h),g=S.G[g]);Q.bindBuffer(34963,g);Q.bufferSubData(34963,0,F.subarray(d,d+e));d=0}Kd(b);
Q.drawElements(a,b,c,d);Ld&&Q.bindBuffer(34962,yd[Q.L]);Q.M||Q.bindBuffer(34963,null)},glEnableVertexAttribArray:function(a){var b=S.U[a];assert(b,a);b.enabled=!0;Q.enableVertexAttribArray(a)},glFramebufferTexture2D:function(a,b,c,d,e){W(Bd,d,"glFramebufferTexture2D","texture");Q.framebufferTexture2D(a,b,c,Bd[d],e)},glGenBuffers:function(a,b){Od(a,b,"createBuffer",yd,"glGenBuffers")},glGenFramebuffers:function(a,b){Od(a,b,"createFramebuffer",Ad,"glGenFramebuffers")},glGenSamplers:function(a,b){Od(a,
b,"createSampler",Ed,"glGenSamplers")},glGenTextures:function(a,b){Od(a,b,"createTexture",Bd,"glGenTextures")},glGenVertexArrays:function(a,b){assert(Q.createVertexArray,"Must have WebGL2 or OES_vertex_array_object to use vao");Od(a,b,"createVertexArray",Dd,"glGenVertexArrays")},glGetIntegerv:function(a,b){Pd(a,b)},glGetShaderInfoLog:function(a,b,c,d){W(U,a,"glGetShaderInfoLog","shader");a=Q.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ka(a,F,d,b):0;c&&(A[c>>2]=b)},glGetShaderiv:function(a,
b,c){c?(W(U,a,"glGetShaderiv","shader"),35716==b?(a=Q.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(U[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=Q.getShaderParameter(U[a],b)):(l("GL_INVALID_VALUE in glGetShaderiv(shader="+a+", pname="+b+", p=0): Function called with null out pointer!"),V(1281))},glGetString:function(a){if(Hd[a])return Hd[a];switch(a){case 7939:var b=Q.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));
b=Qd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:b=Q.getParameter(a);b||(V(1280),l("GL_INVALID_ENUM in glGetString: Received empty parameter for query name "+a+"!"));b=Qd(b);break;case 7938:b=Q.getParameter(7938);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Qd(b);break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Qd(b);break;default:return V(1280),
l("GL_INVALID_ENUM in glGetString: Unknown parameter "+a+"!"),0}return Hd[a]=b},glGetUniformBlockIndex:function(a,b){W(T,a,"glGetUniformBlockIndex","program");return Q.getUniformBlockIndex(T[a],G(b))},glGetUniformLocation:function(a,b){W(T,a,"glGetUniformLocation","program");b=G(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Gd[a]&&Gd[a].Ta[b])&&0<=c&&c<a[0]?a[1]+c:-1},glLinkProgram:function(a){W(T,a,"glLinkProgram","program");
Q.linkProgram(T[a]);W(T,a,"populateUniformTable","program");var b=T[a];a=Gd[a]={Ta:{},Ha:0,Sb:-1,Tb:-1};for(var c=a.Ta,d=Q.getProgramParameter(b,35718),e=0;e<d;++e){var g=Q.getActiveUniform(b,e),h=g.name;a.Ha=Math.max(a.Ha,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=Q.getUniformLocation(b,h);if(m){var n=Jd(Cd);c[h]=[g.size,n];Cd[n]=m;for(var v=1;v<g.size;++v)m=Q.getUniformLocation(b,h+"["+v+"]"),n=Jd(Cd),Cd[n]=m}}},glMapBufferRange:function(a,b,c,d){if(26!=d&&10!=d)return l("glMapBufferRange is only supported when access is MAP_WRITE|INVALIDATE_BUFFER"),
0;if(!Sd(a))return V(1280),l("GL_INVALID_ENUM in glMapBufferRange"),0;var e=Ha(c);if(!e)return 0;zd[Rd(a)]={offset:b,length:c,X:e,ab:d};return e},glSamplerParameteri:function(a,b,c){W(Ed,a,"glBindSampler","sampler");Q.samplerParameteri(Ed[a],b,c)},glShaderSource:function(a,b,c,d){W(U,a,"glShaderSource","shader");for(var e="",g=0;g<b;++g){var h=d?A[d+4*g>>2]:-1;e+=G(A[c+4*g>>2],0>h?void 0:h)}Q.shaderSource(U[a],e)},glTexImage2D:function(a,b,c,d,e,g,h,m,n){if(2<=S.version)if(Q.ja)Q.texImage2D(a,b,c,
d,e,g,h,m,n);else if(n){var v=Td(m);Q.texImage2D(a,b,c,d,e,g,h,m,v,n>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else Q.texImage2D(a,b,c,d,e,g,h,m,null);else Q.texImage2D(a,b,c,d,e,g,h,m,n?Ud(m,h,d,e,n):null)},glTexParameteri:function(a,b,c){Q.texParameteri(a,b,c)},glUniformBlockBinding:function(a,b,c){W(T,a,"glUniformBlockBinding","program");a=T[a];Q.uniformBlockBinding(a,b,c)},glUnmapBuffer:function(a){if(!Sd(a))return V(1280),l("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=Rd(a),c=zd[b];if(!c)return V(1282),
f.Zb("buffer was never mapped in glUnmapBuffer"),0;zd[b]=null;c.ab&16||(2<=S.version?Q.bufferSubData(a,c.offset,F,c.X,c.length):Q.bufferSubData(a,c.offset,F.subarray(c.X,c.X+c.length)));se(c.X);return 1},glUseProgram:function(a){W(T,a,"glUseProgram","program");Q.useProgram(T[a])},glVertexAttribPointer:function(a,b,c,d,e,g){var h=S.U[a];assert(h,a);Q.L?(h.ia=!1,Md(b,c,e,g),Q.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.Ma=d,h.ba=e,h.s=g,h.ia=!0,h.Va=function(m,n,v,t,u,w){this.vertexAttribPointer(m,
n,v,t,u,w)})},glViewport:function(a,b,c,d){Q.viewport(a,b,c,d)},glewInit:function(){return 0},glfwCreateCursor:function(){},glfwCreateStandardCursor:function(){},glfwCreateWindow:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?fd():rd(a,b);for(e=0;e<Y.length&&null==Y[e];e++);e==Y.length&&(f.K=Zc(f.canvas,!0,!0,{antialias:1<Wd[135181],depth:0<Wd[135173],stencil:0<Wd[135174],alpha:0<
Wd[135172]}));f.K?(a=new Vd(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,Z=a,g=a.id):g=0}return g},glfwDestroyCursor:function(){},glfwGetCursorPos:function(a,b,c){r(b,ld,"double");r(c,md,"double")},glfwGetFramebufferSize:function(a,b,c){var d=0,e=0;if(a=X(a))d=a.width,e=a.height;b&&r(b,d,"i32");c&&r(c,e,"i32")},glfwGetKey:function(a,b){return(a=X(a))?a.keys[b]:0},glfwGetKeyName:function(){throw"glfwGetKeyName not implemented.";},glfwGetKeysSiv3D:function(a){a=X(a);if(!a)return 0;a.oa||(a.oa=f.Fb(349));
f.Eb.set(a.keys,a.oa);return a.oa},glfwGetWindowAttrib:function(a,b){return(a=X(a))?a.attributes[b]:0},glfwGetWindowPos:function(a,b,c){var d=0,e=0;if(a=X(a))d=a.x,e=a.y;b&&r(b,d,"i32");c&&r(c,e,"i32")},glfwGetWindowSize:function(a,b,c){var d=0,e=0;if(a=X(a))d=a.width,e=a.height;b&&r(b,d,"i32");c&&r(c,e,"i32")},glfwGetWindowUserPointer:function(a){return(a=X(a))?a.Ua:0},glfwIconifyWindow:function(){},glfwInit:function(){if(Y)return 1;Dc();Wd=Yd;Y=[];Z=null;window.addEventListener("gamepadconnected",
ce,!0);window.addEventListener("gamepaddisconnected",ee,!0);window.addEventListener("keydown",fe,!0);window.addEventListener("keypress",ae,!0);window.addEventListener("keyup",ge,!0);window.addEventListener("blur",he,!0);f.canvas.addEventListener("touchmove",ie,!0);f.canvas.addEventListener("touchstart",me,!0);f.canvas.addEventListener("touchcancel",ne,!0);f.canvas.addEventListener("touchend",ne,!0);f.canvas.addEventListener("mousemove",ie,!0);f.canvas.addEventListener("mousedown",me,!0);f.canvas.addEventListener("mouseup",
ne,!0);f.canvas.addEventListener("wheel",oe,!0);f.canvas.addEventListener("mousewheel",oe,!0);f.canvas.addEventListener("mouseenter",je,!0);f.canvas.addEventListener("mouseleave",ke,!0);f.canvas.addEventListener("drop",te,!0);f.canvas.addEventListener("dragover",ue,!0);qd.push(function(a,b){if(Z){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Z.Ra=Z.x,Z.Sa=Z.y,Z.Qa=Z.width,Z.Pa=Z.height,Z.x=Z.y=0,Z.width=screen.width,Z.height=screen.height,
Z.na=!0):1==Z.na?(Z.x=Z.Ra,Z.y=Z.Sa,Z.width=Z.Qa,Z.height=Z.Pa,Z.na=!1):Z.width!=a||Z.height!=b?(Z.width=a,Z.height=b):c=!1;c&&(rd(Z.width,Z.height,!0),Z&&Z.J&&D.get(Z.J)(Z.id,Z.width,Z.height),Z&&Z.W&&D.get(Z.W)(Z.id,Z.width,Z.height))}});return 1},glfwMakeContextCurrent:function(){},glfwMaximizeWindow:function(){},glfwPollEvents:function(){},glfwRestoreWindow:function(){},glfwSetCursor:function(){},glfwSetCursorPos:function(){},glfwSetErrorCallback:function(a){var b=Xd;Xd=a;return b},glfwSetFramebufferSizeCallback:function(a,
b){a=X(a);if(!a)return null;var c=a.W;a.W=b;return c},glfwSetMouseButtonCallback:function(a,b){if(a=X(a)){var c=a.Z;a.Z=b;b=c}else b=null;return b},glfwSetScrollCallback:function(a,b){if(a=X(a)){var c=a.aa;a.aa=b;b=c}else b=null;return b},glfwSetWindowFocusCallback:function(a,b){a=X(a);if(!a)return null;var c=a.Wa;a.Wa=b;return c},glfwSetWindowIconifyCallback:function(a,b){a=X(a);if(!a)return null;var c=a.Xa;a.Xa=b;return c},glfwSetWindowPos:function(a,b,c){if(a=X(a))a.x=b,a.y=c},glfwSetWindowPosCallback:function(a,
b){a=X(a);if(!a)return null;var c=a.Ya;a.Ya=b;return c},glfwSetWindowShouldClose:function(a,b){if(a=X(a))a.Oa=b},glfwSetWindowSize:function(a,b,c){if(a=X(a))Z.id==a.id&&(b==screen.width&&c==screen.height?fd():(gd(),rd(b,c),a.width=b,a.height=c)),a.J&&D.get(a.J)(a.id,b,c)},glfwSetWindowSizeCallback:function(a,b){if(a=X(a)){var c=a.J;a.J=b;b=c}else b=null;return b},glfwSetWindowSizeLimits:function(){},glfwSetWindowTitle:function(a,b){if(a=X(a))a.title=G(b),Z.id==a.id&&(document.title=a.title)},glfwSetWindowUserPointer:function(a,
b){if(a=X(a))a.Ua=b},glfwSwapBuffers:function(){},glfwSwapInterval:function(a){a=Math.abs(a);0==a?sd(0,0):sd(1,a)},glfwTerminate:function(){window.removeEventListener("gamepadconnected",ce,!0);window.removeEventListener("gamepaddisconnected",ee,!0);window.removeEventListener("keydown",fe,!0);window.removeEventListener("keypress",ae,!0);window.removeEventListener("keyup",ge,!0);window.removeEventListener("blur",he,!0);f.canvas.removeEventListener("touchmove",ie,!0);f.canvas.removeEventListener("touchstart",
me,!0);f.canvas.removeEventListener("touchcancel",ne,!0);f.canvas.removeEventListener("touchend",ne,!0);f.canvas.removeEventListener("mousemove",ie,!0);f.canvas.removeEventListener("mousedown",me,!0);f.canvas.removeEventListener("mouseup",ne,!0);f.canvas.removeEventListener("wheel",oe,!0);f.canvas.removeEventListener("mousewheel",oe,!0);f.canvas.removeEventListener("mouseenter",je,!0);f.canvas.removeEventListener("mouseleave",ke,!0);f.canvas.removeEventListener("drop",te,!0);f.canvas.removeEventListener("dragover",
ue,!0);f.canvas.width=f.canvas.height=1;Z=Y=null},glfwWindowHint:function(a,b){Wd[a]=b},glfwWindowShouldClose:function(a){return(a=X(a))?a.Oa:0},invoke_iii:Je,invoke_iiii:Ke,invoke_iiiii:Le,invoke_vi:Me,invoke_vii:Ne,invoke_viii:Oe,invoke_viiii:Pe,localtime_r:function(a,b){ve();a=new Date(1E3*A[a>>2]);A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),
0,1);A[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;A[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A[b+32>>2]=a;a=A[Ae()+(a?4:0)>>2];A[b+40>>2]=a;return b},memory:Ea,pathconf:function(a,b){return Be(b)},pthread_create:function(){return 6},pthread_detach:function(){},setTempRet0:function(a){va=a|0},strftime:He,strftime_l:function(a,b,c,d){return He(a,b,c,d)},sysconf:function(a){switch(a){case 30:return 16384;
case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}pb(28);return-1},time:function(a){var b=Date.now()/1E3|0;a&&(A[a>>2]=b);return b}};
(function(){function a(e){f.asm=e.exports;db("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return jb().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){l("failed to asynchronously prepare wasm: "+g);q(g)})}var d={env:Qe,wasi_snapshot_preview1:Qe};cb("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(wa||"function"!==typeof WebAssembly.instantiateStreaming||
gb()||eb("file://")||"function"!==typeof fetch)return c(b);fetch(fb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){l("wasm streaming compile failed: "+g);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var kb=f.___wasm_call_ctors=function(){return(kb=f.___wasm_call_ctors=f.asm.__wasm_call_ctors).apply(null,arguments)},se=f._free=function(){return(se=f._free=f.asm.free).apply(null,arguments)},Ha=f._malloc=function(){return(Ha=f._malloc=f.asm.malloc).apply(null,arguments)},qb=f.___errno_location=function(){return(qb=f.___errno_location=f.asm.__errno_location).apply(null,arguments)};f._main=function(){return(f._main=f.asm.main).apply(null,arguments)};
f._realloc=function(){return(f._realloc=f.asm.realloc).apply(null,arguments)};f._saveSetjmp=function(){return(f._saveSetjmp=f.asm.saveSetjmp).apply(null,arguments)};f._testSetjmp=function(){return(f._testSetjmp=f.asm.testSetjmp).apply(null,arguments)};
var Ae=f.__get_tzname=function(){return(Ae=f.__get_tzname=f.asm._get_tzname).apply(null,arguments)},ye=f.__get_daylight=function(){return(ye=f.__get_daylight=f.asm._get_daylight).apply(null,arguments)},xe=f.__get_timezone=function(){return(xe=f.__get_timezone=f.asm._get_timezone).apply(null,arguments)},Ie=f._setThrew=function(){return(Ie=f._setThrew=f.asm.setThrew).apply(null,arguments)},Re=f.stackSave=function(){return(Re=f.stackSave=f.asm.stackSave).apply(null,arguments)},Se=f.stackRestore=function(){return(Se=
f.stackRestore=f.asm.stackRestore).apply(null,arguments)},Pa=f.stackAlloc=function(){return(Pa=f.stackAlloc=f.asm.stackAlloc).apply(null,arguments)};f._emscripten_main_thread_process_queued_calls=function(){return(f._emscripten_main_thread_process_queued_calls=f.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.dynCall_viijii).apply(null,arguments)};
f.dynCall_ji=function(){return(f.dynCall_ji=f.asm.dynCall_ji).apply(null,arguments)};f.dynCall_iij=function(){return(f.dynCall_iij=f.asm.dynCall_iij).apply(null,arguments)};f.dynCall_jij=function(){return(f.dynCall_jij=f.asm.dynCall_jij).apply(null,arguments)};f.dynCall_jiij=function(){return(f.dynCall_jiij=f.asm.dynCall_jiij).apply(null,arguments)};f.dynCall_jiijj=function(){return(f.dynCall_jiijj=f.asm.dynCall_jiijj).apply(null,arguments)};
f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.dynCall_jiji).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.dynCall_iiiiij).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.dynCall_iiiiijj).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.dynCall_iiiiiijj).apply(null,arguments)};f.__growWasmMemory=function(){return(f.__growWasmMemory=f.asm.__growWasmMemory).apply(null,arguments)};
function Je(a,b,c){var d=Re();try{return D.get(a)(b,c)}catch(e){Se(d);if(e!==e+0&&"longjmp"!==e)throw e;Ie(1,0)}}function Oe(a,b,c,d){var e=Re();try{D.get(a)(b,c,d)}catch(g){Se(e);if(g!==g+0&&"longjmp"!==g)throw g;Ie(1,0)}}function Ke(a,b,c,d){var e=Re();try{return D.get(a)(b,c,d)}catch(g){Se(e);if(g!==g+0&&"longjmp"!==g)throw g;Ie(1,0)}}function Le(a,b,c,d,e){var g=Re();try{return D.get(a)(b,c,d,e)}catch(h){Se(g);if(h!==h+0&&"longjmp"!==h)throw h;Ie(1,0)}}
function Me(a,b){var c=Re();try{D.get(a)(b)}catch(d){Se(c);if(d!==d+0&&"longjmp"!==d)throw d;Ie(1,0)}}function Pe(a,b,c,d,e){var g=Re();try{D.get(a)(b,c,d,e)}catch(h){Se(g);if(h!==h+0&&"longjmp"!==h)throw h;Ie(1,0)}}function Ne(a,b,c){var d=Re();try{D.get(a)(b,c)}catch(e){Se(d);if(e!==e+0&&"longjmp"!==e)throw e;Ie(1,0)}}f.addRunDependency=cb;f.removeRunDependency=db;f.FS_createFolder=pc;f.FS_createPath=qc;f.FS_createDataFile=sc;f.FS_createPreloadedFile=wc;f.FS_createLazyFile=vc;f.FS_createLink=tc;
f.FS_createDevice=N;f.FS_unlink=bc;var Te;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}bb=function Ue(){Te||Ve();Te||(bb=Ue)};
function Ve(a){function b(){if(!Te&&(Te=!0,f.calledRun=!0,!Fa)){f.noFSInit||nc||(nc=!0,mc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?N("/dev","stdin",f.stdin):ac("/dev/tty","/dev/stdin"),f.stdout?N("/dev","stdout",null,f.stdout):ac("/dev/tty","/dev/stdout"),f.stderr?N("/dev","stderr",null,f.stderr):ac("/dev/tty1","/dev/stderr"),fc("/dev/stdin","r"),fc("/dev/stdout","w"),fc("/dev/stderr","w"));lb(Wa);Lb=!1;lb(Xa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(We){var c=a,
d=f._main;c=c||[];var e=c.length+1,g=Pa(4*(e+1));A[g>>2]=Oa(da);for(var h=1;h<e;h++)A[(g>>2)+h]=Oa(c[h-1]);A[(g>>2)+e]=0;try{var m=d(e,g);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(f.onExit)f.onExit(m);Fa=!0}ea(m,new qa(m))}}catch(n){n instanceof qa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),l("exception thrown: "+c),ea(1,n)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ya.unshift(c);
lb(Ya)}}a=a||ca;if(!(0<$a)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Za();lb(Va);0<$a||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Ve;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var We=!0;f.noInitialRun&&(We=!1);noExitRuntime=!0;Ve();
